# Generated by Django 3.2.6 on 2021-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210811_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddanceuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
