# Generated by Django 3.2.6 on 2021-08-04 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=300)),
                ('category', models.CharField(choices=[('shorts', 'Shorts'), ('tshirt', 'T-Shirts'), ('blouses', 'Blouses'), ('pants', 'Pants'), ('boots', 'boots'), ('flipflops', 'Flip-flops'), ('tops', 'Tops')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('thumbnail', models.FileField(upload_to='products/thumbnails/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/')),
                ('default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel')),
            ],
        ),
    ]
